# Site settings
title: Mitali Meratwal | Personal website # site title
description: >- # site description
  Personal website of Mitali Meratwal. 
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
# image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/mitali72/mitali72.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Mitali Meratwal # author name
  email: mitalimeratwal@gmail.com # email adress
  avatar: /assets/images/my_pic.jpg # change with your own avatar


# URL settings
url: "https://mitali72.github.io" #
baseurl:
permalink: /posts/:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  parse_block_html: false
  auto_ids: true

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

      
# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess
  - _pages
  
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jemoji
